"""Standalone HTML template for the visual assessment workbench."""

HTML_TEMPLATE = r'''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>VulnAssess Pipeline Workbench - %%TITLE%%</title>
<style>
:root {
  --canvas:#e8eeeb;--surface:#fbfcfa;--surface-2:#f2f5f2;--ink:#17211e;--muted:#63706b;
  --line:#c9d3ce;--line-strong:#94a49d;--rail:#172825;--rail-2:#223a35;--teal:#147d73;
  --teal-soft:#d8ece8;--blue:#2d7189;--blue-soft:#dbeaf0;--amber:#bd7822;--amber-soft:#f7e7ce;
  --red:#a43d35;--red-soft:#f3dcda;--green:#3f7350;--green-soft:#dceadf;--white:#fff;
  --shadow:0 12px 28px rgba(23,40,37,.08);--radius:6px;
}
*{box-sizing:border-box}
html{background:var(--canvas);color:var(--ink);font-family:Bahnschrift,"Aptos Narrow","Segoe UI",sans-serif;letter-spacing:0}
body{margin:0;min-width:320px;min-height:100vh;background-color:var(--canvas);background-image:linear-gradient(rgba(23,40,37,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(23,40,37,.035) 1px,transparent 1px);background-size:28px 28px}
button,select{font:inherit;letter-spacing:0}button{cursor:pointer}
.topbar{height:68px;background:var(--surface);border-bottom:1px solid var(--line);display:grid;grid-template-columns:minmax(220px,1fr) auto minmax(280px,1fr);align-items:center;gap:20px;padding:0 22px;position:sticky;top:0;z-index:30}
.brand{display:flex;align-items:center;gap:11px}.mark{width:34px;height:34px;border:1px solid var(--ink);display:grid;place-items:center;background:var(--white)}.mark svg{width:23px;height:23px;fill:none;stroke:currentColor;stroke-width:1.8}
.brand-name{font-family:Georgia,"Times New Roman",serif;font-size:19px;font-weight:700}.brand-sub{font-size:10px;color:var(--muted);margin-top:2px}
.run-meta{display:flex;align-items:center;justify-content:center;gap:7px}.badge{display:inline-flex;align-items:center;gap:5px;border:1px solid var(--line);background:var(--white);border-radius:4px;padding:5px 8px;font-size:10px;white-space:nowrap}.badge::before{content:"";width:6px;height:6px;border-radius:50%;background:var(--line-strong)}.badge.synthetic{color:var(--amber);border-color:#dfbd8d;background:var(--amber-soft)}.badge.synthetic::before{background:var(--amber)}.badge.ready{color:var(--green);border-color:#9fbea8;background:var(--green-soft)}.badge.ready::before{background:var(--green)}
.replay-controls{display:flex;align-items:center;justify-content:flex-end;gap:7px}.icon-button{width:34px;height:34px;border:1px solid var(--line);border-radius:4px;background:var(--white);display:grid;place-items:center;color:var(--ink)}.icon-button:hover,.icon-button:focus-visible{border-color:var(--teal);box-shadow:0 0 0 3px rgba(20,125,115,.14)}.icon-button svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:2}
.speed{display:flex;border:1px solid var(--line);border-radius:4px;overflow:hidden;background:var(--white)}.speed button{border:0;border-right:1px solid var(--line);background:transparent;padding:8px 9px;font-size:10px;color:var(--muted)}.speed button:last-child{border-right:0}.speed button.active{background:var(--rail);color:var(--white)}
.progress-track{height:4px;background:#d6dfda;position:sticky;top:68px;z-index:29}.progress-value{display:block;height:100%;width:12.5%;background:var(--teal);transition:width .35s ease}
.layout{display:grid;grid-template-columns:244px minmax(0,1fr) 336px;min-height:calc(100vh - 72px);max-width:1800px;margin:0 auto;background:var(--surface);box-shadow:var(--shadow)}
.pipeline-rail{background:var(--rail);color:#d9e5e1;padding:22px 14px 18px;min-width:0}.rail-head{padding:0 9px 16px;border-bottom:1px solid rgba(255,255,255,.12)}.eyebrow{display:block;text-transform:uppercase;font-size:9px;font-weight:700;color:var(--teal);margin-bottom:5px}.pipeline-rail .eyebrow{color:#78c7bd}.rail-head h2{font-family:Georgia,serif;font-size:18px;margin:0}.rail-head p{font-size:10px;line-height:1.45;color:#9eb2ac;margin:7px 0 0}.rail-list{display:grid;gap:2px;margin-top:13px}.rail-stage{border:0;background:transparent;color:#91a49f;text-align:left;display:grid;grid-template-columns:30px 1fr auto;align-items:center;gap:7px;padding:10px 8px;border-left:3px solid transparent;min-height:56px;width:100%}.rail-stage:hover{background:rgba(255,255,255,.04);color:#e7f0ed}.rail-stage.active{background:var(--rail-2);border-left-color:#69c6ba;color:var(--white)}.rail-stage.done{color:#c6d8d2}.rail-index{font-family:Georgia,serif;font-size:15px}.rail-label b{display:block;font-size:11px}.rail-label span{display:block;font-size:9px;color:inherit;opacity:.72;margin-top:3px}.rail-state{width:8px;height:8px;border:1px solid currentColor;border-radius:50%}.rail-stage.done .rail-state{background:#69c6ba;border-color:#69c6ba}.rail-stage.active .rail-state{background:var(--amber);border-color:var(--amber);box-shadow:0 0 0 4px rgba(189,120,34,.18)}
.stage-main{min-width:0;padding:24px 26px 34px;background:var(--surface)}.stage-heading{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;border-bottom:1px solid var(--line);padding-bottom:17px}.stage-title-wrap{min-width:0}.stage-kicker{font-size:10px;color:var(--teal);font-weight:700;text-transform:uppercase}.stage-heading h1{font-family:Georgia,"Times New Roman",serif;font-size:30px;line-height:1.08;margin:5px 0 7px}.stage-heading p{margin:0;color:var(--muted);font-size:12px;line-height:1.5;max-width:720px}.stage-counter{font-family:Georgia,serif;font-size:22px;color:var(--line-strong);white-space:nowrap}.stage-counter b{color:var(--ink)}
.flow-summary{display:grid;grid-template-columns:1fr 38px 1fr 38px 1fr;align-items:stretch;margin:16px 0;border:1px solid var(--line);background:var(--surface-2)}.flow-block{padding:11px 13px;min-width:0}.flow-block span{display:block;font-size:8px;text-transform:uppercase;color:var(--muted);margin-bottom:4px}.flow-block b{font-size:11px;line-height:1.35;display:block}.flow-arrow{display:grid;place-items:center;border-left:1px solid var(--line);border-right:1px solid var(--line);color:var(--teal);font-size:19px;background:var(--white)}
.metric-row{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px;margin-bottom:18px}.metric{border-left:3px solid var(--blue);background:var(--surface-2);padding:9px 11px;min-width:0}.metric.warn{border-color:var(--amber)}.metric.good{border-color:var(--green)}.metric.critical{border-color:var(--red)}.metric b{display:block;font-family:Georgia,serif;font-size:21px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.metric span{font-size:9px;color:var(--muted);text-transform:uppercase}
.stage-content{min-height:420px;animation:stage-in .28s ease}.section-title{display:flex;justify-content:space-between;align-items:end;gap:12px;margin:18px 0 8px}.section-title h2{font-family:Georgia,serif;font-size:18px;margin:0}.section-title p{font-size:10px;color:var(--muted);margin:0}.table-wrap{width:100%;overflow:auto;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}table{border-collapse:collapse;width:100%;font-size:11px}th{text-align:left;color:var(--muted);font-size:8px;text-transform:uppercase;padding:8px 9px;background:var(--surface-2);border-bottom:1px solid var(--line);position:sticky;top:0}td{padding:9px;border-bottom:1px solid #e0e6e2;vertical-align:top}tbody tr:last-child td{border-bottom:0}tbody tr.selectable{cursor:pointer}tbody tr.selectable:hover,tbody tr.selected{background:#e7f2ef}.mono{font-family:Consolas,"Cascadia Mono",monospace;font-size:10px;overflow-wrap:anywhere}.muted{color:var(--muted)}.strong{font-weight:700}.nowrap{white-space:nowrap}.truncate{display:block;max-width:360px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.status{display:inline-flex;align-items:center;border-radius:3px;padding:3px 6px;font-size:9px;font-weight:700;background:var(--surface-2);color:var(--muted);white-space:nowrap}.status.ok{background:var(--green-soft);color:var(--green)}.status.warn{background:var(--amber-soft);color:var(--amber)}.status.info{background:var(--blue-soft);color:var(--blue)}.status.bad{background:var(--red-soft);color:var(--red)}
.host-strip{display:flex;gap:6px;overflow:auto;padding-bottom:8px}.host-chip{border:1px solid var(--line);background:var(--white);border-radius:4px;padding:7px 10px;font-size:10px;color:var(--muted);white-space:nowrap}.host-chip.active{border-color:var(--teal);background:var(--teal-soft);color:var(--ink);font-weight:700}
.split{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(260px,.85fr);gap:18px}.data-block{min-width:0;border-top:2px solid var(--ink);padding-top:10px}.data-block h3{font-family:Georgia,serif;font-size:16px;margin:0 0 4px}.data-block>p{font-size:10px;color:var(--muted);line-height:1.45;margin:0 0 10px}.record-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.record{border:1px solid var(--line);border-radius:4px;background:var(--white);padding:10px;min-width:0}.record.active{border-color:var(--teal);box-shadow:inset 3px 0 0 var(--teal)}.record-head{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.record h4{font-size:11px;margin:0}.record p{font-size:10px;color:var(--muted);line-height:1.4;margin:7px 0 0}.evidence{border-left:3px solid var(--amber);background:#fbf1e1;padding:9px 10px;font:10px/1.5 Consolas,"Cascadia Mono",monospace;overflow-wrap:anywhere;margin-top:9px}
.probability-list{display:grid;gap:7px}.probability-row{display:grid;grid-template-columns:128px 1fr 48px;gap:8px;align-items:center;font-size:10px}.bar-track{height:9px;background:#dfe6e2;border:1px solid #c8d2cd;border-radius:2px;overflow:hidden}.bar-fill{height:100%;width:0;background:var(--blue);transition:width .55s ease}.probability-row.winner .bar-fill{background:var(--teal)}.probability-row.winner{font-weight:700}.probability-value{text-align:right;font-variant-numeric:tabular-nums}
.thresholds{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-bottom:10px}.threshold{background:var(--surface-2);padding:8px}.threshold b{display:block;font-family:Georgia,serif;font-size:17px}.threshold span{font-size:8px;color:var(--muted);text-transform:uppercase}
.feature-list{display:grid;gap:5px}.feature-row{display:grid;grid-template-columns:minmax(110px,1fr) 52px minmax(120px,1.4fr);gap:7px;padding:7px 0;border-bottom:1px solid #e0e6e2;font-size:10px}.feature-row:last-child{border-bottom:0}
.context-matrix{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.context-host{border:1px solid var(--line);border-top:3px solid var(--teal);padding:11px;background:var(--white);min-width:0}.context-host h3{font-size:12px;margin:0 0 8px}.fact{display:grid;grid-template-columns:84px 1fr auto;gap:7px;border-top:1px solid #e4e9e6;padding:7px 0;font-size:10px}.fact:first-of-type{border-top:0}.confidence{font-variant-numeric:tabular-nums;color:var(--blue)}
.vector{font:10px/1.5 Consolas,"Cascadia Mono",monospace;padding:9px;background:var(--rail);color:#e8f2ef;overflow-wrap:anywhere}.vector-diff{display:flex;gap:5px;flex-wrap:wrap;margin-top:8px}.vector-token{border:1px solid var(--line);background:var(--surface-2);padding:4px 6px;border-radius:3px;font:9px Consolas,monospace}.vector-token.changed{background:var(--amber-soft);border-color:#ddb57e;color:#845111}
.score-bridge{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px;align-items:stretch}.score-node{border:1px solid var(--line);background:var(--white);padding:10px;position:relative;min-height:92px}.score-node:not(:last-child)::after{content:"›";position:absolute;right:-7px;top:33px;z-index:2;width:14px;height:24px;background:var(--surface);display:grid;place-items:center;color:var(--teal);font-size:20px}.score-node span{display:block;font-size:8px;color:var(--muted);text-transform:uppercase}.score-node b{display:block;font-family:Georgia,serif;font-size:24px;margin-top:8px}.score-node small{display:block;font-size:9px;color:var(--muted);margin-top:4px}.score-node.final{background:var(--red-soft);border-color:#d59a95}.score-node.final b{color:var(--red)}
.equation{background:var(--rail);color:#e9f2ef;font:12px/1.55 Consolas,monospace;padding:12px;margin-top:10px;overflow:auto}.queue-table{min-width:760px}.rank-cell{font-family:Georgia,serif;font-size:17px}.risk-cell{font-family:Georgia,serif;font-size:17px;font-weight:700}.delta.up{color:var(--green)}.delta.down{color:var(--red)}.band{display:inline-block;padding:4px 7px;border-radius:3px;font-size:9px;font-weight:700}.band.Critical{background:var(--red-soft);color:var(--red)}.band.High{background:var(--amber-soft);color:#8c5819}.band.Medium{background:var(--blue-soft);color:var(--blue)}.band.Low{background:var(--green-soft);color:var(--green)}
.comparison-band{display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--line);margin-top:14px}.compare-item{padding:13px}.compare-item+ .compare-item{border-left:1px solid var(--line)}.compare-top{display:flex;justify-content:space-between;gap:10px}.compare-risk{font-family:Georgia,serif;font-size:28px}.compare-item dl{display:grid;grid-template-columns:1fr auto;gap:5px 10px;font-size:10px;margin:10px 0 0}.compare-item dt{color:var(--muted)}.compare-item dd{margin:0;font-weight:700}
.trace-strip{margin-top:22px;border-top:1px solid var(--line);padding-top:14px}.trace-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.trace-head h2{font-family:Georgia,serif;font-size:16px;margin:0}.trace-head span{font-size:9px;color:var(--muted)}.trace-path{display:grid;grid-template-columns:repeat(6,1fr);margin-top:9px;border:1px solid var(--line)}.trace-step{padding:9px;border-right:1px solid var(--line);min-width:0;background:var(--surface-2);opacity:.42}.trace-step:last-child{border-right:0}.trace-step.unlocked{opacity:1;background:var(--white)}.trace-step.active{box-shadow:inset 0 -3px 0 var(--teal);background:var(--teal-soft)}.trace-step span{display:block;font-size:8px;color:var(--muted);text-transform:uppercase}.trace-step b{display:block;font-size:10px;margin-top:4px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.inspector{border-left:1px solid var(--line);background:#f5f7f5;padding:22px 18px;min-width:0}.inspector-sticky{position:sticky;top:92px}.inspector h2{font-family:Georgia,serif;font-size:18px;margin:0}.inspector-lead{font-size:10px;color:var(--muted);line-height:1.45;margin:5px 0 12px}.entity-select{width:100%;border:1px solid var(--line);background:var(--white);border-radius:4px;padding:8px;font-size:10px;color:var(--ink)}.inspect-section{border-top:1px solid var(--line);padding-top:11px;margin-top:12px}.inspect-section h3{font-size:9px;text-transform:uppercase;color:var(--muted);margin:0 0 7px}.inspect-grid{display:grid;grid-template-columns:86px 1fr;gap:6px 9px;font-size:10px}.inspect-grid dt{color:var(--muted)}.inspect-grid dd{margin:0;overflow-wrap:anywhere}.raw-quote{font:10px/1.5 Consolas,"Cascadia Mono",monospace;background:var(--white);border:1px solid var(--line);padding:9px;max-height:128px;overflow:auto}.ledger{display:grid}.ledger-item{display:grid;grid-template-columns:23px 1fr;gap:8px;padding:7px 0;border-top:1px solid #dde4e0;opacity:.4}.ledger-item.done,.ledger-item.active{opacity:1}.ledger-dot{width:19px;height:19px;border:1px solid var(--line-strong);border-radius:50%;display:grid;place-items:center;font-size:8px}.ledger-item.done .ledger-dot{background:var(--green);border-color:var(--green);color:white}.ledger-item.active .ledger-dot{background:var(--amber);border-color:var(--amber);color:white}.ledger-item b{font-size:10px;display:block}.ledger-item span{font-size:9px;color:var(--muted);display:block;margin-top:2px;line-height:1.35}
.page-footer{grid-column:1/-1;border-top:1px solid var(--line);background:var(--surface-2);display:flex;justify-content:space-between;gap:16px;padding:10px 18px;font-size:9px;color:var(--muted)}
@keyframes stage-in{from{opacity:.2;transform:translateY(5px)}to{opacity:1;transform:none}}
@media(max-width:1180px){.layout{grid-template-columns:220px minmax(0,1fr)}.inspector{grid-column:1/-1;border-left:0;border-top:1px solid var(--line)}.inspector-sticky{position:static;display:grid;grid-template-columns:240px 1fr 1fr;gap:16px}.inspector-sticky>.inspect-section{margin-top:0}.topbar{grid-template-columns:1fr auto}.run-meta{display:none}}
@media(max-width:760px){.topbar{height:auto;min-height:64px;grid-template-columns:1fr auto;padding:10px 12px}.brand-sub{display:none}.speed{display:none}.progress-track{top:64px}.layout{display:block}.pipeline-rail{padding:10px 8px}.rail-head{display:none}.rail-list{display:flex;overflow:auto;margin:0}.rail-stage{min-width:132px;min-height:48px;grid-template-columns:24px 1fr;padding:7px;border-left:0;border-bottom:3px solid transparent}.rail-stage.active{border-bottom-color:#69c6ba}.rail-state{display:none}.stage-main{padding:17px 12px 28px}.stage-heading h1{font-size:25px}.stage-counter{font-size:17px}.flow-summary{grid-template-columns:1fr}.flow-arrow{height:24px;border:0;border-top:1px solid var(--line);border-bottom:1px solid var(--line);font-size:0}.flow-arrow::after{content:"↓";font-size:15px}.metric-row{grid-template-columns:1fr 1fr}.split,.context-matrix{grid-template-columns:1fr}.record-grid{grid-template-columns:1fr}.score-bridge{grid-template-columns:1fr 1fr}.score-node:not(:last-child)::after{display:none}.comparison-band{grid-template-columns:1fr}.compare-item+ .compare-item{border-left:0;border-top:1px solid var(--line)}.trace-path{display:flex;overflow:auto}.trace-step{min-width:126px}.inspector{padding:18px 12px}.inspector-sticky{display:block}.page-footer{display:block}.page-footer span{display:block;margin-top:4px}.probability-row{grid-template-columns:105px 1fr 42px}.thresholds{grid-template-columns:1fr 1fr 1fr}}
@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
</style>
</head>
<body>
<header class="topbar">
  <div class="brand"><div class="mark" aria-hidden="true"><svg viewBox="0 0 24 24"><path d="M12 2 20 5v6c0 5.2-3.3 8.4-8 10.5C7.3 19.4 4 16.2 4 11V5l8-3Z"/><path d="M7.5 12h3l1.5-4 2.2 8 1.4-4H19"/></svg></div><div><div class="brand-name">VulnAssess</div><div class="brand-sub">Evidence-led prioritisation workbench</div></div></div>
  <div class="run-meta"><span class="badge synthetic">Synthetic data · not run</span><span class="badge ready" id="runBadge">Run</span><span class="badge" id="modelBadge">Model</span></div>
  <div class="replay-controls"><button class="icon-button" id="restart" title="Restart replay" aria-label="Restart replay"><svg viewBox="0 0 24 24"><path d="M4 12a8 8 0 1 0 2.3-5.7L4 8"/><path d="M4 3v5h5"/></svg></button><button class="icon-button" id="play" title="Play replay" aria-label="Play replay"><svg id="playIcon" viewBox="0 0 24 24"><path d="m8 5 11 7-11 7Z"/></svg></button><div class="speed" aria-label="Replay speed"><button data-speed="1500">0.5x</button><button class="active" data-speed="850">1x</button><button data-speed="460">2x</button></div></div>
</header>
<div class="progress-track"><span class="progress-value" id="progressValue"></span></div>
<div class="layout">
  <aside class="pipeline-rail"><div class="rail-head"><span class="eyebrow">Assessment pipeline</span><h2>Decision path</h2><p>Each stage owns one transformation. Select a stage to inspect its input, rule and output.</p></div><nav class="rail-list" id="stageRail" aria-label="Assessment stages"></nav></aside>
  <main class="stage-main">
    <header class="stage-heading"><div class="stage-title-wrap"><span class="stage-kicker" id="stageKicker">Stage 01</span><h1 id="stageTitle">Scope fence</h1><p id="stageDescription"></p></div><div class="stage-counter"><b id="stageNumber">01</b> / 08</div></header>
    <section class="flow-summary" id="flowSummary" aria-label="Stage transformation"></section>
    <section class="metric-row" id="stageMetrics" aria-label="Stage metrics"></section>
    <section class="stage-content" id="stageContent"></section>
    <section class="trace-strip"><div class="trace-head"><h2>Selected finding trace</h2><span id="traceIdentity"></span></div><div class="trace-path" id="tracePath"></div></section>
  </main>
  <aside class="inspector"><div class="inspector-sticky"><div><span class="eyebrow">Evidence inspector</span><h2>Canonical record</h2><p class="inspector-lead">The selected finding remains linked to its source while every downstream decision is exposed.</p><select class="entity-select" id="findingSelect" aria-label="Selected finding"></select></div><section class="inspect-section" id="recordInspector"></section><section class="inspect-section"><h3>Decision ledger</h3><div class="ledger" id="decisionLedger"></div></section></div></aside>
  <footer class="page-footer"><span>No external assets, scripts, feeds or model calls. Synthetic arithmetic cannot establish H1-H4.</span><span id="footerHash"></span></footer>
</div>
<script>const DATA=%%PAYLOAD%%;
const state={stage:0,playing:false,speed:850,selectedFinding:DATA.ranked?.[0]?.finding_id||null,selectedHost:DATA.hosts?.[0]?.ip||null,timer:null};
const icons={play:'<path d="m8 5 11 7-11 7Z"/>',pause:'<path d="M8 5v14M16 5v14"/>'};
const stageFlow=[
  ['Configured lab targets','Exact IP allow-list + canary refusal','Authorised target set'],
  ['Scanner-native records','Canonical schema + stable fingerprint','Provenance-preserving findings'],
  ['Canonical findings + local feeds','Explicit CVE / CPE range matching','Dated enrichment records'],
  ['Observed host features','Calibrated multinomial classifier','Shadow role probabilities'],
  ['Services + findings + scope','Deterministic context rules','Evidence-backed context profile'],
  ['Base CVSS vector + context','Modified metrics and requirements','Environmental CVSS vector'],
  ['Environmental score + feed facts','EPSS multiplier + conditional KEV rule','Auditable risk value'],
  ['All deterministic scores','Risk descending + stable ID tie-break','Prioritised remediation queue']
];
const stageShort=['Fence','Normalise','Match','Predict','Infer','Modify','Overlay','Rank'];
function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmt(value,digits=1){return value===null||value===undefined?'—':Number(value).toFixed(digits)}
function pct(value){return value===null||value===undefined?'—':`${Math.round(Number(value)*100)}%`}
function finding(){return DATA.ranked.find(item=>item.finding_id===state.selectedFinding)||DATA.ranked[0]}
function host(){return DATA.hosts.find(item=>item.ip===state.selectedHost)||DATA.hosts[0]}
function selectFinding(id){const item=DATA.ranked.find(row=>row.finding_id===id);if(!item)return;state.selectedFinding=id;state.selectedHost=item.host_ip;renderAll()}
function selectHost(ip){state.selectedHost=ip;const first=DATA.ranked.find(item=>item.host_ip===ip);if(first)state.selectedFinding=first.finding_id;renderAll()}
function metric(value,label,tone=''){return `<div class="metric ${tone}"><b>${esc(value)}</b><span>${esc(label)}</span></div>`}
function status(text,tone='info'){return `<span class="status ${tone}">${esc(text)}</span>`}
function sectionTitle(title,note=''){return `<div class="section-title"><h2>${esc(title)}</h2><p>${esc(note)}</p></div>`}
function hostStrip(){return `<div class="host-strip">${DATA.hosts.map(item=>`<button class="host-chip ${item.ip===state.selectedHost?'active':''}" data-select-host="${esc(item.ip)}">${esc(item.ip)} · ${esc(item.rule_role?.value||'unknown')}</button>`).join('')}</div>`}
function bindDynamic(){document.querySelectorAll('[data-select-finding]').forEach(el=>el.addEventListener('click',()=>selectFinding(el.dataset.selectFinding)));document.querySelectorAll('[data-select-host]').forEach(el=>el.addEventListener('click',()=>selectHost(el.dataset.selectHost)))}
function scopeStage(){const rows=DATA.hosts.map(item=>`<tr><td class="mono">${esc(item.ip)}</td><td>${esc(item.hostname||'none observed')}</td><td>${item.services.length}</td><td>${esc(item.segment||'unknown')}</td><td>${status('authorised','ok')}</td></tr>`).join('');return {metrics:[metric(DATA.scope.allowed.length,'explicit targets','good'),metric(DATA.pipeline_counts.hosts,'observed hosts'),metric(DATA.scope.canary,'canary address','warn'),metric('0','discovery sweeps','good')],content:`${sectionTitle('Authorisation decision','Target checks precede capture access')}<div class="split"><div class="data-block"><h3>Explicit target ledger</h3><p>A CIDR boundary is not treated as permission to discover hosts.</p><div class="table-wrap"><table><thead><tr><th>IP</th><th>Hostname</th><th>Services</th><th>Segment</th><th>Gate</th></tr></thead><tbody>${rows}</tbody></table></div></div><div class="data-block"><h3>Canary safeguard</h3><p>The out-of-scope canary is a refusal target, never a scan destination.</p><div class="record active"><div class="record-head"><h4>${esc(DATA.scope.canary)}</h4>${status('blocked before file access','ok')}</div><div class="evidence">ScopeError → no command built → no scanner subprocess</div></div><div class="record"><div class="record-head"><h4>Authorisation result</h4>${status('closed','ok')}</div><p>${DATA.scope.allowed.length} exact hosts accepted. No implicit CIDR-wide discovery.</p></div></div></div>`}}
function ingestStage(){const toolRows=Object.entries(DATA.tool_counts).sort().map(([tool,count])=>`<div class="record"><div class="record-head"><h4>${esc(tool.toUpperCase())}</h4>${status(`${count} findings`,'info')}</div><p>Native records retained beside canonical UUIDs.</p></div>`).join('');const rows=DATA.ranked.map(item=>`<tr class="selectable ${item.finding_id===state.selectedFinding?'selected':''}" data-select-finding="${esc(item.finding_id)}"><td>${esc(item.tool)}</td><td class="mono">${esc(item.tool_native_id)}</td><td class="mono">${esc(item.finding_id)}</td><td>${esc(item.host_ip)}:${esc(item.port??'—')}</td><td><span class="truncate">${esc(item.title)}</span></td><td class="mono">${esc(item.provenance.raw_path)} #${item.provenance.record_index}</td></tr>`).join('');return {metrics:[metric(DATA.pipeline_counts.canonical_findings,'canonical findings'),metric(Object.keys(DATA.tool_counts).length,'source tools'),metric(DATA.pipeline_counts.hosts,'hosts'),metric('100%','provenance retained','good')],content:`${sectionTitle('Native records become one schema','Select a row to follow it through the pipeline')}<div class="record-grid">${toolRows}</div><div class="table-wrap"><table><thead><tr><th>Tool</th><th>Native ID</th><th>Canonical ID</th><th>Asset</th><th>Finding</th><th>Raw provenance</th></tr></thead><tbody>${rows}</tbody></table></div>`}}
function intelStage(){const feedRows=Object.entries(DATA.feeds).map(([name,feed])=>`<tr><td class="strong">${esc(name.toUpperCase())}</td><td>${esc(feed.file_date||'unknown')}</td><td>${feed.rows}</td><td class="mono">${esc(String(feed.sha256||'').slice(0,18))}…</td><td>${status('local snapshot','ok')}</td></tr>`).join('');const matchRows=DATA.ranked.map(item=>{const enrich=item.enrichment;return `<tr class="selectable ${item.finding_id===state.selectedFinding?'selected':''}" data-select-finding="${esc(item.finding_id)}"><td><span class="truncate">${esc(item.title)}</span></td><td>${esc(item.cve||'unmatched')}</td><td>${enrich?status(enrich.match_method,'info'):status('native fallback','warn')}</td><td>${enrich?fmt(enrich.match_confidence,2):'—'}</td><td>${fmt(item.base_score,1)}</td><td>${pct(item.epss_percentile)}</td><td>${item.kev?status('listed','bad'):status('not listed')}</td></tr>`}).join('');return {metrics:[metric(Object.keys(DATA.feeds).length,'offline feeds','good'),metric(DATA.pipeline_counts.enriched_findings,'findings enriched'),metric(DATA.pipeline_counts.enrichment_records,'match records'),metric(DATA.pipeline_counts.unique_cves,'unique CVEs')],content:`<div class="split"><div class="data-block"><h3>Feed ledger</h3><p>Each join remains tied to a dated local file digest.</p><div class="table-wrap"><table><thead><tr><th>Feed</th><th>Date</th><th>Rows</th><th>SHA-256</th><th>Source</th></tr></thead><tbody>${feedRows}</tbody></table></div></div><div class="data-block"><h3>Matching policy</h3><p>Explicit scanner CVEs lead; CPE range matches remain confidence-scored.</p><div class="evidence">finding → explicit CVE | compatible CPE range → NVD + EPSS + KEV</div></div></div>${sectionTitle('Per-finding enrichment decisions','No feed row is silently invented')}<div class="table-wrap"><table><thead><tr><th>Finding</th><th>CVE</th><th>Method</th><th>Confidence</th><th>CVSS</th><th>EPSS %ile</th><th>KEV</th></tr></thead><tbody>${matchRows}</tbody></table></div>`}}
function modelStage(){const item=host(),p=item.prediction;const probabilities=Object.entries(p.probabilities).sort((a,b)=>b[1]-a[1]).map(([label,value],index)=>`<div class="probability-row ${index===0?'winner':''}"><span>${esc(label.replaceAll('_',' '))}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.max(0,Math.min(100,value*100))}%"></div></div><span class="probability-value">${pct(value)}</span></div>`).join('');const contributors=(p.contributors||[]).map(row=>`<div class="feature-row"><span class="mono">${esc(row.feature)}</span><span>${fmt(row.weight,3)}</span><span class="mono muted">${esc(row.evidence)}</span></div>`).join('')||'<div class="evidence">No positive contributor survived preprocessing.</div>';return {metrics:[metric(DATA.model.classes.length,'role classes'),metric(DATA.model.features,'trained features'),metric(fmt(p.confidence,3),'top probability',p.abstained?'warn':'good'),metric(fmt(p.margin,3),'top-two margin')],content:`${hostStrip()}<div class="split"><div class="data-block"><h3>Class probability distribution</h3><p>Prediction is shadow-only and cannot alter a score.</p><div class="probability-list">${probabilities}</div></div><div class="data-block"><h3>Decision boundary</h3><p>Confidence, margin, feature coverage and structural support all gate the output.</p><div class="thresholds"><div class="threshold"><b>${fmt(DATA.model.confidence_threshold,2)}</b><span>confidence floor</span></div><div class="threshold"><b>${fmt(DATA.model.margin_threshold,2)}</b><span>margin floor</span></div><div class="threshold"><b>${pct(p.feature_coverage)}</b><span>feature coverage</span></div></div><div class="record active"><div class="record-head"><h4>${p.abstained?'Abstained → unknown':esc(p.label.replaceAll('_',' '))}</h4>${status(p.structural_support?'structural support':'no structural support',p.structural_support?'ok':'warn')}</div><p>OOV features: ${esc((p.out_of_vocabulary||[]).join(', ')||'none')}</p></div></div></div>${sectionTitle('Positive feature contributors','Weights are paired with observed evidence')}<div class="feature-list">${contributors}</div>`}}
function contextStage(){const cards=DATA.hosts.map(item=>{const controls=Object.entries(item.controls||{}).map(([name,f])=>`<div class="fact"><span>${esc(name)}</span><b>${esc(String(f.value))}</b><span class="confidence">${fmt(f.confidence,2)}</span></div>`).join('')||'<div class="fact"><span>controls</span><b>none observed</b><span>—</span></div>';return `<button class="context-host" data-select-host="${esc(item.ip)}" style="text-align:left"><h3>${esc(item.ip)}</h3><div class="fact"><span>rule role</span><b>${esc(item.rule_role?.value||'unknown')}</b><span class="confidence">${fmt(item.rule_role?.confidence,2)}</span></div><div class="fact"><span>model</span><b>${esc(item.prediction.label)}</b><span class="confidence">${fmt(item.prediction.confidence,2)}</span></div><div class="fact"><span>exposure</span><b>${esc(item.exposure?.value||'unknown')}</b><span class="confidence">${fmt(item.exposure?.confidence,2)}</span></div>${controls}<div class="evidence">${esc(item.rule_role?.evidence||'none observed')}</div></button>`}).join('');const selected=host();const facts=[['role',selected.rule_role],['exposure',selected.exposure],...Object.entries(selected.controls||{})].map(([name,f])=>`<tr><td>${esc(name)}</td><td>${esc(f?.value??'none observed')}</td><td>${fmt(f?.confidence,2)}</td><td>${esc(f?.source||'rule')}</td><td class="mono">${esc(f?.evidence||'none observed')}</td></tr>`).join('');return {metrics:[metric(DATA.pipeline_counts.context_profiles,'context profiles'),metric(DATA.hosts.filter(h=>h.exposure?.value==='internet_facing').length,'internet-facing','warn'),metric(DATA.hosts.filter(h=>h.prediction.label!==h.rule_role?.value).length,'rule/model differences'),metric('0','model-written scores','good')],content:`${sectionTitle('Host context matrix','Rule inference remains authoritative')}<div class="context-matrix">${cards}</div>${sectionTitle(`Evidence ledger · ${selected.ip}`,'Every feature carries confidence, source and quote')}<div class="table-wrap"><table><thead><tr><th>Feature</th><th>Value</th><th>Confidence</th><th>Source</th><th>Verbatim evidence</th></tr></thead><tbody>${facts}</tbody></table></div>`}}
function vectorMap(vector){const result={};String(vector||'').split('/').slice(1).forEach(token=>{const [key,value]=token.split(':');if(key)result[key]=value});return result}
function environmentStage(){const item=finding(),base=vectorMap(item.base_vector),env=vectorMap(item.env_vector);const keys=[...new Set([...Object.keys(base),...Object.keys(env),...Object.keys(item.env_modifications||{})])];const tokens=keys.map(key=>{const value=env[key]||item.env_modifications?.[key]||base[key];const changed=key.startsWith('M')||['CR','IR','AR'].includes(key);return `<span class="vector-token ${changed&&item.env_modifications?.[key]?'changed':''}">${esc(key)}:${esc(value)}</span>`}).join('');const rows=DATA.ranked.map(row=>`<tr class="selectable ${row.finding_id===state.selectedFinding?'selected':''}" data-select-finding="${esc(row.finding_id)}"><td><span class="truncate">${esc(row.title)}</span></td><td>${esc(row.host_ip)}</td><td>${fmt(row.base_score,1)}</td><td>${fmt(row.env_score,1)}</td><td>${row.base_score===null||row.env_score===null?'—':fmt(row.env_score-row.base_score,1)}</td><td class="mono">${esc(Object.entries(row.env_modifications||{}).map(([k,v])=>`${k}:${v}`).join(' ')||'none')}</td></tr>`).join('');return {metrics:[metric(fmt(item.base_score,1),'base CVSS'),metric(fmt(item.env_score,1),'environmental CVSS',item.env_score!==item.base_score?'warn':''),metric(Object.keys(item.env_modifications||{}).length,'modified metrics'),metric(esc(item.role||'unknown'),'asset role')],content:`${hostStrip()}<div class="split"><div class="data-block"><h3>Published base vector</h3><p>Technical severity from the matched vulnerability record.</p><div class="vector">${esc(item.base_vector||'No CVSS vector; native fallback')}</div></div><div class="data-block"><h3>Context-adjusted vector</h3><p>Only configured, evidence-backed modifications are applied.</p><div class="vector">${esc(item.env_vector||'No environmental vector')}</div><div class="vector-diff">${tokens}</div></div></div>${sectionTitle('Environmental effect across findings','Select a row to inspect vector changes')}<div class="table-wrap"><table><thead><tr><th>Finding</th><th>Host</th><th>Base</th><th>Environmental</th><th>Delta</th><th>Applied modifications</th></tr></thead><tbody>${rows}</tbody></table></div>`}}
function threatStage(){const item=finding(),env=item.env_score??item.base_score??item.risk/10,mult=item.threat_multiplier,preThreat=env*10,withThreat=mult===null?preThreat:preThreat*mult,boost=item.kev?DATA.weights.kev_boost:0;const nodes=[['Environmental',fmt(env,1),'CVSS context'],['Scale ×10',fmt(preThreat,1),'priority scale'],['Threat',mult===null?'unscored':fmt(mult,3),item.epss_percentile===null?'EPSS missing':`EPSS ${pct(item.epss_percentile)}`],['KEV',item.kev?`+${boost}`:'+0',item.kev?'known exploited':'not listed'],['Final',fmt(item.risk,1),item.band]];const rows=DATA.ranked.map(row=>`<tr class="selectable ${row.finding_id===state.selectedFinding?'selected':''}" data-select-finding="${esc(row.finding_id)}"><td><span class="truncate">${esc(row.title)}</span></td><td>${fmt(row.env_score,1)}</td><td>${pct(row.epss_percentile)}</td><td>${row.threat_multiplier===null?'unscored':fmt(row.threat_multiplier,3)}</td><td>${row.kev?status('yes','bad'):status('no')}</td><td class="risk-cell">${fmt(row.risk,1)}</td></tr>`).join('');return {metrics:[metric(pct(item.epss_percentile),'EPSS percentile'),metric(mult===null?'unscored':fmt(mult,3),'threat multiplier'),metric(item.kev?'listed':'not listed','CISA KEV',item.kev?'critical':''),metric(fmt(item.risk,1),'final risk',item.band==='Critical'?'critical':'')],content:`${sectionTitle('Deterministic score reconstruction',item.title)}<div class="score-bridge">${nodes.map((node,index)=>`<div class="score-node ${index===4?'final':''}"><span>${esc(node[0])}</span><b>${esc(node[1])}</b><small>${esc(node[2])}</small></div>`).join('')}</div><div class="equation">${esc(item.env_score??item.base_score)} × 10 × ${esc(mult??'unscored')} + ${boost} = ${fmt(item.risk,1)} · weights ${esc(item.weights_hash)}</div>${sectionTitle('Threat overlay across the assessment','Same CVE always receives the same feed facts')}<div class="table-wrap"><table><thead><tr><th>Finding</th><th>Environmental</th><th>EPSS %ile</th><th>Multiplier</th><th>KEV</th><th>Risk</th></tr></thead><tbody>${rows}</tbody></table></div>`}}
function rankStage(){const rows=DATA.ranked.map(item=>{const delta=item.rank_delta;const deltaText=delta>0?`↑ ${delta}`:delta<0?`↓ ${Math.abs(delta)}`:'—';return `<tr class="selectable ${item.finding_id===state.selectedFinding?'selected':''}" data-select-finding="${esc(item.finding_id)}"><td class="rank-cell">${item.position}</td><td class="risk-cell">${fmt(item.risk,1)}</td><td><span class="band ${esc(item.band)}">${esc(item.band)}</span></td><td class="mono">${esc(item.host_ip)}:${esc(item.port??'—')}</td><td><b>${esc(item.title)}</b><br><span class="muted">${esc(item.reason)}</span></td><td>${item.baseline_position}</td><td class="delta ${delta>0?'up':delta<0?'down':''}">${deltaText}</td></tr>`}).join('');const comparison=DATA.comparison.map(item=>`<div class="compare-item"><div class="compare-top"><div><span class="muted mono">${esc(item.host_ip)}</span><div class="strong">${esc(String(item.role).replaceAll('_',' '))}</div></div><span class="band ${esc(item.band)}">${esc(item.band)}</span></div><div class="compare-risk">${fmt(item.risk,1)}</div><dl><dt>CVSS base</dt><dd>${fmt(item.base_score,1)}</dd><dt>Environmental</dt><dd>${fmt(item.env_score,1)}</dd><dt>Exposure</dt><dd>${esc(item.exposure)}</dd><dt>EPSS / KEV</dt><dd>${pct(item.epss_percentile)} / ${item.kev?'yes':'no'}</dd></dl></div>`).join('');return {metrics:[metric(DATA.ranked.length,'ranked findings'),metric(DATA.ranked.filter(i=>i.band==='Critical').length,'critical','critical'),metric(DATA.ranked.filter(i=>i.kev).length,'KEV findings','warn'),metric(Math.max(...DATA.ranked.map(i=>Math.abs(i.rank_delta))),'largest rank shift')],content:`${sectionTitle('Remediation queue','Context-aware rank beside CVSS-only position')}<div class="table-wrap"><table class="queue-table"><thead><tr><th>Rank</th><th>Risk</th><th>Band</th><th>Asset</th><th>Finding and deterministic reason</th><th>CVSS-only</th><th>Movement</th></tr></thead><tbody>${rows}</tbody></table></div>${sectionTitle('Same CVE. Same base. Different operational risk.','Context is the only host-specific scoring input')}<div class="comparison-band">${comparison}</div>`}}
const stageRenderers=[scopeStage,ingestStage,intelStage,modelStage,contextStage,environmentStage,threatStage,rankStage];
function renderRail(){document.getElementById('stageRail').innerHTML=DATA.stages.map((item,index)=>`<button class="rail-stage ${index===state.stage?'active':index<state.stage?'done':''}" data-stage="${index}"><span class="rail-index">${String(index+1).padStart(2,'0')}</span><span class="rail-label"><b>${esc(item.name)}</b><span>${esc(stageShort[index])}</span></span><span class="rail-state"></span></button>`).join('');document.querySelectorAll('[data-stage]').forEach(el=>el.addEventListener('click',()=>setStage(Number(el.dataset.stage))))}
function renderFlow(){const flow=stageFlow[state.stage];document.getElementById('flowSummary').innerHTML=`<div class="flow-block"><span>Input</span><b>${esc(flow[0])}</b></div><div class="flow-arrow">›</div><div class="flow-block"><span>Decision</span><b>${esc(flow[1])}</b></div><div class="flow-arrow">›</div><div class="flow-block"><span>Output</span><b>${esc(flow[2])}</b></div>`}
function renderTrace(){const item=finding();const steps=[['Scanner',`${item.tool} · ${item.tool_native_id}`],['CVE match',item.cve||'unmatched'],['Context',`${item.role||'unknown'} · ${item.exposure||'unknown'}`],['CVSS env',item.env_score===null?'native fallback':`${item.base_score} → ${item.env_score}`],['Threat',item.threat_multiplier===null?'unscored':`${item.threat_multiplier}${item.kev?' + KEV':''}`],['Queue',`#${item.position} · ${item.risk} ${item.band}`]];const unlock=[1,2,4,5,6,7];document.getElementById('traceIdentity').textContent=`${item.host_ip} · ${item.finding_id.slice(0,8)}`;document.getElementById('tracePath').innerHTML=steps.map((step,index)=>`<div class="trace-step ${state.stage>=unlock[index]?'unlocked':''} ${state.stage===unlock[index]?'active':''}"><span>${esc(step[0])}</span><b>${state.stage>=unlock[index]?esc(step[1]):'locked'}</b></div>`).join('')}
function renderInspector(){const item=finding(),profile=DATA.hosts.find(h=>h.ip===item.host_ip);document.getElementById('findingSelect').innerHTML=DATA.ranked.map(row=>`<option value="${esc(row.finding_id)}" ${row.finding_id===item.finding_id?'selected':''}>#${row.position} · ${esc(row.host_ip)} · ${esc(row.title)}</option>`).join('');document.getElementById('recordInspector').innerHTML=`<h3>Source and identity</h3><dl class="inspect-grid"><dt>Canonical ID</dt><dd class="mono">${esc(item.finding_id)}</dd><dt>Native ID</dt><dd class="mono">${esc(item.tool_native_id)}</dd><dt>Asset</dt><dd>${esc(item.host_ip)}:${esc(item.port??'—')}/${esc(item.protocol||'—')}</dd><dt>Raw file</dt><dd class="mono">${esc(item.provenance.raw_path)}</dd><dt>Record</dt><dd>${item.provenance.record_index}</dd><dt>Rule context</dt><dd>${esc(profile?.rule_role?.value||'unknown')} · ${fmt(profile?.rule_role?.confidence,2)}</dd><dt>Model</dt><dd>${esc(profile?.prediction?.label||'unknown')} · ${fmt(profile?.prediction?.confidence,2)}${profile?.prediction?.abstained?' · abstained':''}</dd></dl><div class="inspect-section"><h3>Verbatim scanner evidence</h3><div class="raw-quote">${esc(item.evidence)}</div></div>`;const ledgerText=[`Allowed asset ${item.host_ip}`,`${item.tool} record → canonical ID`,item.enrichment?`${item.enrichment.match_method} → ${item.cve}`:'native severity fallback',`Model ${profile?.prediction?.abstained?'abstained':`suggested ${profile?.prediction?.label}`}`,`Rule role ${item.role}; exposure ${item.exposure}`,item.env_vector?`Environmental score ${item.env_score}`:'No environmental vector',item.threat_multiplier===null?'EPSS unscored':`Threat multiplier ${item.threat_multiplier}`,`Rank #${item.position} at ${item.risk}`];document.getElementById('decisionLedger').innerHTML=ledgerText.map((text,index)=>`<div class="ledger-item ${index<state.stage?'done':index===state.stage?'active':''}"><span class="ledger-dot">${index+1}</span><div><b>${esc(DATA.stages[index].name)}</b><span>${index<=state.stage?esc(text):'pending'}</span></div></div>`).join('')}
function renderStage(){const stage=DATA.stages[state.stage],view=stageRenderers[state.stage]();document.getElementById('stageKicker').textContent=`Stage ${String(state.stage+1).padStart(2,'0')} · ${stageShort[state.stage]}`;document.getElementById('stageTitle').textContent=stage.name;document.getElementById('stageDescription').textContent=stage.description;document.getElementById('stageNumber').textContent=String(state.stage+1).padStart(2,'0');document.getElementById('stageMetrics').innerHTML=view.metrics.join('');document.getElementById('stageContent').innerHTML=view.content;document.getElementById('progressValue').style.width=`${((state.stage+1)/DATA.stages.length)*100}%`;renderFlow();renderTrace();renderInspector();bindDynamic()}
function renderAll(){renderRail();renderStage()}
function setStage(index){if(state.playing)pause();state.stage=Math.max(0,Math.min(DATA.stages.length-1,index));renderAll()}
function play(){if(state.stage===DATA.stages.length-1)state.stage=-1;state.playing=true;document.getElementById('playIcon').innerHTML=icons.pause;document.getElementById('play').title='Pause replay';const tick=()=>{if(!state.playing)return;if(state.stage>=DATA.stages.length-1){pause();return}state.stage+=1;renderAll();state.timer=setTimeout(tick,state.speed)};tick()}
function pause(){state.playing=false;clearTimeout(state.timer);document.getElementById('playIcon').innerHTML=icons.play;document.getElementById('play').title='Play replay'}
document.getElementById('runBadge').textContent=`Run ${DATA.run_id}`;document.getElementById('modelBadge').textContent=`Model ${DATA.model.hash}`;document.getElementById('footerHash').textContent=`model ${DATA.model.hash} · run ${DATA.run_id}`;document.getElementById('play').addEventListener('click',()=>state.playing?pause():play());document.getElementById('restart').addEventListener('click',()=>{pause();state.stage=0;renderAll()});document.querySelectorAll('[data-speed]').forEach(button=>button.addEventListener('click',()=>{state.speed=Number(button.dataset.speed);document.querySelectorAll('[data-speed]').forEach(item=>item.classList.toggle('active',item===button));if(state.playing){pause();play()}}));document.getElementById('findingSelect').addEventListener('change',event=>selectFinding(event.target.value));renderAll();
</script>
</body>
</html>'''